pipeline {
    agent any

    stages {
        stage('Cloning project') {
            steps {
                git branch: 'master', credentialsId: 'JenkinsDaroz', url: 'https://github.com/geraldodf/mind-log.git'
            }
        }

        stage('Build image') {
            steps {
                sh 'docker build -t daroz/mind-log-web:latest ./mind-log-web'
            }
        }

        stage('Stop and remove the previous version') {
            steps {
                sh 'docker stop mind-log-web || true && docker rm mind-log-web || true'
            }
        }

        stage('Run application') {
            steps {
                sh 'docker-compose -f ./mind-log-web/docker-compose.yml up -d'
            }
        }

        stage('Log container') {
            steps {
                sleep(time: 5, unit: 'SECONDS')
                sh 'docker logs mind-log-web'
            }
        }
    }
}
