pipeline {
    agent any

    environment {
        DB_HOST = credentials('DB_HOST')
        DB_PORT = credentials('DB_PORT')
        DB_USER = credentials('DB_USER')
        DB_NAME = credentials('MIND_LOG_DB_NAME')
        DB_PASSWORD = credentials('DB_PASSWORD')
        ACCESS_TOKEN = credentials('MIND_LOG_ACCESS_TOKEN')
        REFRESH_TOKEN = credentials('MIND_LOG_REFRESH_TOKEN')
        JWT_DURATION_ACCESS = credentials('JWT_DURATION_ACCESS')
        JWT_DURATION_REFRESH = credentials('JWT_DURATION_REFRESH')
        CORS_ORIGINS = credentials('MIND_LOG_CORS_ORIGINS')
        PASSWORD_RECOVER_TOKEN_MINUTES = credentials('PASSWORD_RECOVER_TOKEN_MINUTES')
        PASSWORD_RECOVER_TOKEN_URI = credentials('MIND_LOG_PASSWORD_RECOVER_TOKEN_URI')
        GOOGLE_CLIENT_ID = credentials('MIND_LOG_GOOGLE_CLIENT_ID')
        GOOGLE_CLIENT_SECRET = credentials('MIND_LOG_GOOGLE_CLIENT_SECRET')
        OAUTH2_SUCCESS_REDIRECT_URI = credentials('MIND_LOG_OAUTH2_SUCCESS_REDIRECT_URI')
    }

    stages {
        stage('Cloning project') {
            steps {
                git branch: 'master', credentialsId: 'JenkinsDaroz', url: 'https://github.com/geraldodf/mind-log.git'
            }
        }

        stage('Build image') {
            steps {
                sh 'docker build -t daroz/mind-log-api:latest ./mind-log-api'
            }
        }

        stage('Stop and remove the previous version') {
            steps {
                sh 'docker stop mind-log-api || true && docker rm mind-log-api || true'
            }
        }

        stage('Run application') {
            steps {
                sh '''
                    DB_HOST=${DB_HOST} DB_PORT=${DB_PORT} DB_USER=${DB_USER} DB_PASSWORD=${DB_PASSWORD} DB_NAME=${DB_NAME} \
                    ACCESS_TOKEN=${ACCESS_TOKEN} REFRESH_TOKEN=${REFRESH_TOKEN} REFRESH_TOKEN=${REFRESH_TOKEN} \
                    JWT_DURATION_ACCESS=${JWT_DURATION_ACCESS} JWT_DURATION_REFRESH=${JWT_DURATION_REFRESH} \
                    CORS_ORIGINS=${CORS_ORIGINS} \
                    PASSWORD_RECOVER_TOKEN_MINUTES=${PASSWORD_RECOVER_TOKEN_MINUTES} PASSWORD_RECOVER_TOKEN_URI=${PASSWORD_RECOVER_TOKEN_URI} \
                    GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID} GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET} \
                    OAUTH2_SUCCESS_REDIRECT_URI=${OAUTH2_SUCCESS_REDIRECT_URI} \
                    docker-compose -f ./mind-log-api/docker-compose.yml up -d
                '''
            }
        }

        stage('Log container') {
            steps {
                sleep(time: 10, unit: 'SECONDS')
                sh 'docker logs mind-log-api'
            }
        }
    }
}
