spring.application.name=MindLog

server.servlet.context-path=/api
server.port=8080

spring.threads.virtual.enabled=true
spring.jpa.open-in-view=false

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

spring.security.accessToken.secret=${ACCESS_TOKEN}
spring.security.refreshToken.secret=${REFRESH_TOKEN}
security.jwt.duration.access=${JWT_DURATION_ACCESS}
security.jwt.duration.refresh=${JWT_DURATION_REFRESH}

spring.security.cors.origins=${CORS_ORIGINS}

security.password.recover.token.minutes=${PASSWORD_RECOVER_TOKEN_MINUTES}
security.password.recover.token.uri=${PASSWORD_RECOVER_TOKEN_URI}

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
security.oauth2.success-redirect-uri=${OAUTH2_SUCCESS_REDIRECT_URI}
