spring.application.name="MindLog"

server.servlet.context-path=/api
server.port=8080

spring.profiles.active=${APP_PROFILE:dev}

spring.jpa.open-in-view=false

spring.threads.virtual.enabled = true

spring.security.accessToken.secret=${ACCESS_TOKEN:myaccesstoken}
spring.security.refreshToken.secret=${REFRESH_TOKEN:myrefreshtoken}
security.jwt.duration.access=${JWT_DURATION_ACCESS:3600}
security.jwt.duration.refresh=${JWT_DURATION_REFRESH:90}
spring.security.cors.origins=${CORS_ORIGINS:http://localhost:4200}
security.password.recover.token.minutes=${PASSWORD_RECOVER_TOKEN_MINUTES:30}
security.password.recover.token.uri=${PASSWORD_RECOVER_TOKEN_URI:http://localhost:4200/auth/reset-password}

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:123}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:123}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
security.oauth2.success-redirect-uri=${OAUTH2_SUCCESS_REDIRECT_URI:http://localhost:4200/auth/callback}
